#!/system/bin/sh
#PROJECT DARK BOOSTER - ABS Tweaks
#Version - 5.0
#Devoloped by dark_optimistic @XDA
#Copyright (C)2015 dark_optimistic
#==============================================================#
#========================= Licenses ===========================#
#==============================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#==============================================================#
#======================= Important Note =======================#
#==============================================================#
#If you want to use my mod in your ROM than you don't need to take permission from me. All you need to is just give ME ( dark_optimistic @XDA) proper CREDITS.
#
#If you want to share my mod on your blog/website/Fb page or any other place than please do not reupload it. Simply give original Android File Host Download link provided on my XDA Thread. 
#
#Do not try to Rename or Modify ABS Tweaks. If I found you doing this than ready to face consequences. I will report you wherever you are.
#
#For more info check out my website - <http://www.techflue.com/>  & also see Licenses given below.
#==============================================================#

busybox=system/etc/PDB-ABS/Extras/busybox

mount -o rw,remount / 2>/dev/null
mount -o rw,remount / / 2>/dev/null
mount -o rw,remount rootfs 2>/dev/null
mount -o rw,remount /system 2>/dev/null
mount -o rw,remount /system /system 2>/dev/null
$busybox mount -o rw,remount / 2>/dev/null
$busybox mount -o rw,remount / / 2>/dev/null
$busybox mount -o rw,remount rootfs 2>/dev/null
$busybox mount -o rw,remount /system 2>/dev/null
$busybox mount -o rw,remount /system /system 2>/dev/null

ABS=/system/etc/PDB-ABS/Extras/ABS_Logs/PDB_Profiler.log

$busybox rm -f $ABS
$busybox touch $ABS

$busybox echo "# ABS log " | $busybox tee -a $ABS
$busybox echo "" | $busybox tee -a $ABS
$busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Starting Gaming Profile" | $busybox tee -a $ABS

# Cost
if [ -e /sys/module/lowmemorykiller/parameters/cost ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/cost
$busybox echo "16" > /sys/module/lowmemorykiller/parameters/cost
fi

# Debug level
if [ -e /sys/module/lowmemorykiller/parameters/debug_level ]; then
$busybox chmod 644 /sys/modulëe/lowmemorykiller/parameters/debug_level
$busybox echo "0" > /sys/module/lowmemorykiller/parameters/debug_level
fi

# Minfree Values 
mem=`$busybox awk '/MemTotal/{print $2}' /proc/meminfo`

#512 and less
oom11=8
oom21=12
oom31=18
oom41=24
oom51=117
oom61=248

lmk11=$(($oom11*1024/4));
lmk21=$(($oom21*1024/4));
lmk31=$(($oom31*1024/4));
lmk41=$(($oom41*1024/4));
lmk51=$(($oom51*1024/4));
lmk61=$(($oom61*1024/4));

#768
oom12=14
oom22=30
oom32=62
oom42=128
oom52=172
oom62=248

lmk12=$(($oom12*1024/4));
lmk22=$(($oom22*1024/4));
lmk32=$(($oom32*1024/4));
lmk42=$(($oom42*1024/4));
lmk52=$(($oom52*1024/4));
lmk62=$(($oom62*1024/4));

#1024
oom13=16
oom23=32
oom33=64
oom43=128
oom53=185
oom63=248

lmk13=$(($oom13*1024/4));
lmk23=$(($oom23*1024/4));
lmk33=$(($oom33*1024/4));
lmk43=$(($oom43*1024/4));
lmk53=$(($oom53*1024/4));
lmk63=$(($oom63*1024/4));

#1536
oom14=32
oom24=64
oom34=92
oom44=130
oom54=187
oom64=252

lmk14=$(($oom14*1024/4));
lmk24=$(($oom24*1024/4));
lmk34=$(($oom34*1024/4));
lmk44=$(($oom44*1024/4));
lmk54=$(($oom54*1024/4));
lmk64=$(($oom64*1024/4));

#2048
oom15=32
oom25=52
oom35=75
oom45=157
oom55=210
oom65=256

lmk15=$(($oom15*1024/4));
lmk25=$(($oom25*1024/4));
lmk35=$(($oom35*1024/4));
lmk45=$(($oom45*1024/4));
lmk55=$(($oom55*1024/4));
lmk65=$(($oom65*1024/4));

#3072
oom16=42
oom26=64
oom36=78
oom46=152
oom56=220
oom66=264

lmk16=$(($oom16*1024/4));
lmk26=$(($oom26*1024/4));
lmk36=$(($oom36*1024/4));
lmk46=$(($oom46*1024/4));
lmk56=$(($oom56*1024/4));
lmk66=$(($oom66*1024/4));

#3072+
oom17=48
oom27=72
oom37=84
oom47=156
oom57=224
oom67=264

lmk17=$(($oom17*1024/4));
lmk27=$(($oom27*1024/4));
lmk37=$(($oom37*1024/4));
lmk47=$(($oom47*1024/4));
lmk57=$(($oom57*1024/4));
lmk67=$(($oom67*1024/4));

if [ "$mem" -lt 524288 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk11,$lmk21,$lmk31,$lmk41,$lmk51,$lmk61" > /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "" >> $ABS
$busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Gaming Profile for your 512MB RAM device successfully applied" | $busybox $busybox tee -a $ABS
elif [ "$mem" -lt 786432 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk12,$lmk22,$lmk32,$lmk42,$lmk52,$lmk62" >/sys/module/lowmemorykiller/parameters/minfree
$busybox echo "" >> $ABS
$busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Gaming Profile for your 768MB RAM device successfully applied" | $busybox $busybox tee -a $ABS
elif [ "$mem" -lt 1048576 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk13,$lmk23,$lmk33,$lmk43,$lmk53,$lmk63" > /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "" >> $ABS
$busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Gaming Profile for your 1GB RAM device successfully applied" | $busybox $busybox tee -a $ABS
elif [ "$mem" -lt 1572864 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk14,$lmk24,$lmk34,$lmk44,$lmk54,$lmk64" > /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "" >> $ABS
$busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Gaming Profile for your 1.5GB RAM device successfully applied" | $busybox $busybox tee -a $ABS
elif [ "$mem" -lt 2097152 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk15,$lmk25,$lmk35,$lmk45,$lmk55,$lmk65" > /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "" >> $ABS
$busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Gaming Profile for your 2GB RAM device successfully applied" | $busybox $busybox tee -a $ABS
elif [ "$mem" -lt 3145728 ]; then
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk16,$lmk26,$lmk36,$lmk46,$lmk56,$lmk66" > /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "" >> $ABS
$busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Gaming Profile for your 3GB RAM device successfully applied" | $busybox $busybox tee -a $ABS
else 
$busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "$lmk17,$lmk27,$lmk37,$lmk47,$lmk57,$lmk67" > /sys/module/lowmemorykiller/parameters/minfree
$busybox echo "" >> $ABS
$busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Gaming Profile for your 4GB RAM device successfully applied" | $busybox $busybox tee -a $ABS
fi
