#!/system/bin/sh
#PROJECT DARK BOOSTER - ABS Tweaks
#Version - 5.0
#Devoloped by dark_optimistic @XDA
#Copyright (C)2015 dark_optimistic
#==============================================================#
#========================= Licenses ===========================#
#==============================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#==============================================================#
#======================= Important Note =======================#
#==============================================================#
#If you want to use my mod in your ROM than you don't need to take permission from me. All you need to is just give ME ( dark_optimistic @XDA) proper CREDITS.
#
#If you want to share my mod on your blog/website/Fb page or any other place than please do not reupload it. Simply give original Android File Host Download link provided on my XDA Thread. 
#
#Do not try to Rename or Modify ABS Tweaks. If I found you doing this than ready to face consequences. I will report you wherever you are.
#
#For more info check out my website - <http://www.techflue.com/>  & also see Licenses given below.
#==============================================================#



busybox sleep 5

READ_AHEAD_KB="2048"

if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/179:0/read_ahead_kb
fi
if [ -e /sys/devices/virtual/bdi/179:8/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/179:8/read_ahead_kb
fi
if [ -e /sys/devices/virtual/bdi/179:16/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/179:16/read_ahead_kb
fi
if [ -e /sys/devices/virtual/bdi/179:24/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/179:24/read_ahead_kb
fi
if [ -e /system/bin/make_ext4fs ]; then
    mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodiratime,barrier=0,nobh /cache /cache
    mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodiratime,barrier=0,nobh /data /data
fi
if [ -e /proc/sys/vm/drop_caches ]; then
    echo "3" > /proc/sys/vm/drop_caches
fi
if [ -e /proc/sys/vm/panic_on_oom ]; then
    echo "3" > /proc/sys/vm/panic_on_oom
fi
if [ -e /proc/sys/vm/stat_interval ]; then
    echo "1" > /proc/sys/vm/stat_interval
fi
if [ -e /proc/sys/vm/mmap_min_addr ]; then
    echo "0" > /proc/sys/vm/mmap_min_addr
fi
if [ -e /proc/sys/vm/overcommit_memory ]; then
    echo "1" > /proc/sys/vm/overcommit_memory
fi
if [ -e /proc/sys/vm/min_free_kbytes ]; then
    echo "16384" > /proc/sys/vm/min_free_kbytes
fi
if [ -e /proc/sys/vm/min_free_order_shift ]; then
    echo "5" > /proc/sys/vm/min_free_order_shift
fi
if [ -e /proc/sys/vm/highmem_is_dirtyable ]; then
    echo "1" > /proc/sys/vm/highmem_is_dirtyable
fi
if [ -e /proc/sys/vm/scan_unevictable_pages ]; then
    echo "0" > /proc/sys/vm/scan_unevictable_pages
fi
if [ -e /proc/sys/vm/oom_kill_allocating_task ]; then
    echo "1" > /proc/sys/vm/oom_kill_allocating_task
fi
if [ -e /proc/sys/vm/dirty_background_ratio ]; then
    echo "60" > /proc/sys/vm/dirty_background_ratio
fi
if [ -e /proc/sys/vm/dirty_expire_centisecs ]; then
    echo "1000" > /proc/sys/vm/dirty_expire_centisecs
fi
if [ -e /proc/sys/vm/dirty_ratio ]; then
    echo "65" > /proc/sys/vm/dirty_ratio
fi
if [ -e /proc/sys/vm/dirty_writeback_centisecs ]; then
    echo "2000" > /proc/sys/vm/dirty_writeback_centisecs
fi
if [ -e /proc/sys/vm/swappiness ]; then
    echo "30" > /proc/sys/vm/swappiness
fi
if [ -e /proc/sys/vm/vfs_cache_pressure ]; then
    echo "40" > /proc/sys/vm/vfs_cache_pressure